version: '1.0.0'

networks:
  my_network:

services:
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: memory
      MYSQL_ROOT_PASSWORD: memory20240409
    networks:
      - my_network
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d

  backend:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/memory?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: memory20240409
    networks:
      - my_network
    restart: always
