spring:
  profiles:
    active: prod
  banner:
    charset: UTF-8
    location: banner.text
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${mysql.host:localhost}:${mysql.port}/${mysql.database}
#    username: ${mysql.username}
#    password: ${mysql.password}
    hikari:
      max-lifetime: 120000
logging:
  config: classpath:logback-blog.xml

mybatis:
  configuration:
    map-underscore-to-camel-case: true


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'Memory Blog接口文档'
      paths-to-match: '/**'
      packages-to-scan: com.linmoblog.server.Controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

blog:
  minio:
    endpoint: http://127.0.0.1:9000 # Minio服务所在地址
    bucketName: memory # 存储桶名称
    accessKey: memory # 访问的key
    secretKey: memory # 访问的秘钥
