name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create timestamp
      id: timestamp
      run: echo "::set-output name=time::$(date +%s)"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag karensky/memory_core:${{ github.sha }}
    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push image to Docker Hub
      run: docker push karensky/memory_core:${{ github.sha }}
